// <auto-generated />
using System;
using GiTinder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GiTinder.Migrations
{
    [DbContext(typeof(GiTinderContext))]
    [Migration("20181213130915_AddedNewUsersFilipAndJonthanToTheController")]
    partial class AddedNewUsersFilipAndJonthanToTheController
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("GiTinder.Models.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("GiTinder.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ReposCount");

                    b.Property<string>("UserName");

                    b.Property<int?>("UserSettingsId");

                    b.Property<string>("UserToken");

                    b.HasKey("Id");

                    b.HasIndex("UserSettingsId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GiTinder.Models.User", b =>
                {
                    b.HasOne("GiTinder.Models.Settings", "UserSettings")
                        .WithMany()
                        .HasForeignKey("UserSettingsId");
                });
#pragma warning restore 612, 618
        }
    }
}
