using Microsoft.EntityFrameworkCore.Migrations;

namespace GiTinder.Migrations
{
    public partial class CreatedNewPropertiesInSettingsModelAndAutoGeneratedSettingsControllerAndAddedNewSettingsUnitTests : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<short>(
                name: "EnableNotification",
                table: "Settings",
                nullable: false,
                defaultValue: (short)0);

            migrationBuilder.AddColumn<int>(
                name: "MaxDistanceInKm",
                table: "Settings",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<string>(
                name: "PreferredLanguages",
                table: "Settings",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "EnableNotification",
                table: "Settings");

            migrationBuilder.DropColumn(
                name: "MaxDistanceInKm",
                table: "Settings");

            migrationBuilder.DropColumn(
                name: "PreferredLanguages",
                table: "Settings");
        }
    }
}
