<<<<<<< HEAD
﻿using GiTinder.Data;
=======
﻿// <auto-generated />
using GiTinder.Data;
>>>>>>> 86ace2f0f4fee38e0556e02328d08e632d49bf24
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GiTinder.Migrations
{
    [DbContext(typeof(GiTinderContext))]
    partial class GiTinderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("GiTinder.Models.User", b =>
                {
<<<<<<< HEAD
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<string>("Repos");

                    b.Property<int>("ReposCount");

                    b.Property<string>("UserName");

                    b.Property<string>("UserToken");

                    b.HasKey("Id");
=======
                    b.Property<string>("UserName")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ReposCount");

                    b.Property<string>("UserToken")
                        .IsRequired();

                    b.HasKey("UserName");
>>>>>>> 86ace2f0f4fee38e0556e02328d08e632d49bf24

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
